<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 16,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            5 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            6 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            7 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            8 => 
            array (
                'id' => 21,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            9 => 
            array (
                'id' => 23,
                'data_type_id' => 4,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            10 => 
            array (
                'id' => 24,
                'data_type_id' => 4,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            11 => 
            array (
                'id' => 25,
                'data_type_id' => 4,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            12 => 
            array (
                'id' => 26,
                'data_type_id' => 4,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            13 => 
            array (
                'id' => 55,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            14 => 
            array (
                'id' => 56,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            15 => 
            array (
                'id' => 57,
                'data_type_id' => 7,
                'field' => 'linetype_id',
                'type' => 'text',
                'display_name' => 'Linetype Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            16 => 
            array (
                'id' => 58,
                'data_type_id' => 7,
                'field' => 'remark',
                'type' => 'text',
                'display_name' => 'Remark',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            17 => 
            array (
                'id' => 59,
                'data_type_id' => 7,
                'field' => 'update_by',
                'type' => 'text',
                'display_name' => 'Update By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            18 => 
            array (
                'id' => 60,
                'data_type_id' => 7,
                'field' => 'input_by',
                'type' => 'text',
                'display_name' => 'Input By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            19 => 
            array (
                'id' => 61,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            20 => 
            array (
                'id' => 62,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 8,
            ),
            21 => 
            array (
                'id' => 63,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 64,
                'data_type_id' => 8,
                'field' => 'line_id',
                'type' => 'select_dropdown',
                'display_name' => 'Line Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 65,
                'data_type_id' => 8,
                'field' => 'lineprocess_id',
                'type' => 'select_dropdown',
                'display_name' => 'Lineprocess Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            24 => 
            array (
                'id' => 66,
                'data_type_id' => 8,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            25 => 
            array (
                'id' => 67,
                'data_type_id' => 8,
                'field' => 'mac_address',
                'type' => 'text',
                'display_name' => 'Mac Address',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            26 => 
            array (
                'id' => 68,
                'data_type_id' => 8,
                'field' => 'ip_address',
                'type' => 'text',
                'display_name' => 'Ip Address',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            27 => 
            array (
                'id' => 69,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            28 => 
            array (
                'id' => 70,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 8,
            ),
            29 => 
            array (
                'id' => 71,
                'data_type_id' => 8,
                'field' => 'scanner_belongsto_line_relationship',
                'type' => 'relationship',
                'display_name' => 'lines',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Line","table":"lines","type":"belongsTo","column":"line_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            30 => 
            array (
                'id' => 72,
                'data_type_id' => 4,
                'field' => 'department_hasone_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"hasOne","column":"department_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            31 => 
            array (
                'id' => 73,
                'data_type_id' => 7,
                'field' => 'line_hasmany_scanner_relationship',
                'type' => 'relationship',
                'display_name' => 'scanners',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Scanner","table":"scanners","type":"hasMany","column":"line_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            32 => 
            array (
                'id' => 74,
                'data_type_id' => 7,
                'field' => 'line_belongsto_linetype_relationship',
                'type' => 'relationship',
                'display_name' => 'linetypes',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Linetype","table":"linetypes","type":"belongsTo","column":"linetype_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            33 => 
            array (
                'id' => 81,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            34 => 
            array (
                'id' => 82,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 1,
            ),
            35 => 
            array (
                'id' => 83,
                'data_type_id' => 10,
                'field' => 'type',
                'type' => 'select_dropdown',
                'display_name' => 'Type',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"option1","options":{"1":"Internal","2":"External","3":"Chamber"}}',
                'order' => 3,
            ),
            36 => 
            array (
                'id' => 84,
                'data_type_id' => 10,
                'field' => 'std_time',
                'type' => 'text',
                'display_name' => 'Std Time',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            37 => 
            array (
                'id' => 85,
                'data_type_id' => 10,
                'field' => 'endpoint_id',
                'type' => 'text',
                'display_name' => 'Endpoint Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            38 => 
            array (
                'id' => 86,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            39 => 
            array (
                'id' => 87,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            40 => 
            array (
                'id' => 88,
                'data_type_id' => 10,
                'field' => 'lineprocess_belongsto_endpoint_relationship',
                'type' => 'relationship',
                'display_name' => 'endpoints',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Endpoint","table":"endpoints","type":"belongsTo","column":"endpoint_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            41 => 
            array (
                'id' => 89,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            42 => 
            array (
                'id' => 90,
                'data_type_id' => 11,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            43 => 
            array (
                'id' => 91,
                'data_type_id' => 11,
                'field' => 'remark',
                'type' => 'text',
                'display_name' => 'Remark',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            44 => 
            array (
                'id' => 92,
                'data_type_id' => 11,
                'field' => 'input_by',
                'type' => 'text',
                'display_name' => 'Input By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            45 => 
            array (
                'id' => 93,
                'data_type_id' => 11,
                'field' => 'update_by',
                'type' => 'text',
                'display_name' => 'Update By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            46 => 
            array (
                'id' => 94,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            47 => 
            array (
                'id' => 95,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            48 => 
            array (
                'id' => 96,
                'data_type_id' => 11,
                'field' => 'linetype_hasmany_line_relationship',
                'type' => 'relationship',
                'display_name' => 'lines',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Line","table":"lines","type":"hasMany","column":"linetype_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            49 => 
            array (
                'id' => 97,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            50 => 
            array (
                'id' => 98,
                'data_type_id' => 12,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            51 => 
            array (
                'id' => 99,
                'data_type_id' => 12,
                'field' => 'line_id',
                'type' => 'text',
                'display_name' => 'Line Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            52 => 
            array (
                'id' => 100,
                'data_type_id' => 12,
                'field' => 'process',
                'type' => 'text',
                'display_name' => 'Process',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            53 => 
            array (
                'id' => 101,
                'data_type_id' => 12,
                'field' => 'update_by',
                'type' => 'text',
                'display_name' => 'Update By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            54 => 
            array (
                'id' => 102,
                'data_type_id' => 12,
                'field' => 'input_by',
                'type' => 'text',
                'display_name' => 'Input By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            55 => 
            array (
                'id' => 103,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            56 => 
            array (
                'id' => 104,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 8,
            ),
            57 => 
            array (
                'id' => 105,
                'data_type_id' => 12,
                'field' => 'sequence_belongsto_line_relationship',
                'type' => 'relationship',
                'display_name' => 'lines',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Line","table":"lines","type":"belongsTo","column":"line_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            58 => 
            array (
                'id' => 106,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            59 => 
            array (
                'id' => 107,
                'data_type_id' => 13,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            60 => 
            array (
                'id' => 108,
                'data_type_id' => 13,
                'field' => 'url',
                'type' => 'text',
                'display_name' => 'Url',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            61 => 
            array (
                'id' => 109,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            62 => 
            array (
                'id' => 110,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            63 => 
            array (
                'id' => 111,
                'data_type_id' => 13,
                'field' => 'endpoint_hasmany_lineprocess_relationship',
                'type' => 'relationship',
                'display_name' => 'lineprocesses',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Lineprocess","table":"lineprocesses","type":"hasMany","column":"endpoint_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            64 => 
            array (
                'id' => 119,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            65 => 
            array (
                'id' => 120,
                'data_type_id' => 16,
                'field' => 'role_id',
                'type' => 'select_multiple',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            66 => 
            array (
                'id' => 121,
                'data_type_id' => 16,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            67 => 
            array (
                'id' => 122,
                'data_type_id' => 16,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            68 => 
            array (
                'id' => 123,
                'data_type_id' => 16,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 6,
            ),
            69 => 
            array (
                'id' => 124,
                'data_type_id' => 16,
                'field' => 'nik',
                'type' => 'text',
                'display_name' => 'Nik',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"maxlength":6}',
                'order' => 2,
            ),
            70 => 
            array (
                'id' => 125,
                'data_type_id' => 16,
                'field' => 'access_id',
                'type' => 'text',
                'display_name' => 'Access Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 8,
            ),
            71 => 
            array (
                'id' => 126,
                'data_type_id' => 16,
                'field' => 'input_by',
                'type' => 'text',
                'display_name' => 'Input By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 9,
            ),
            72 => 
            array (
                'id' => 127,
                'data_type_id' => 16,
                'field' => 'update_by',
                'type' => 'text',
                'display_name' => 'Update By',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 10,
            ),
            73 => 
            array (
                'id' => 128,
                'data_type_id' => 16,
                'field' => 'grade_id',
                'type' => 'select_dropdown',
                'display_name' => 'Grade Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 11,
            ),
            74 => 
            array (
                'id' => 129,
                'data_type_id' => 16,
                'field' => 'department_id',
                'type' => 'select_dropdown',
                'display_name' => 'Department Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 12,
            ),
            75 => 
            array (
                'id' => 130,
                'data_type_id' => 16,
                'field' => 'password',
                'type' => 'text',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"password":true}',
                'order' => 5,
            ),
            76 => 
            array (
                'id' => 131,
                'data_type_id' => 16,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 13,
            ),
            77 => 
            array (
                'id' => 132,
                'data_type_id' => 16,
                'field' => 'settings',
                'type' => 'text',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 14,
            ),
            78 => 
            array (
                'id' => 133,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 15,
            ),
            79 => 
            array (
                'id' => 134,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 16,
            ),
            80 => 
            array (
                'id' => 135,
                'data_type_id' => 16,
                'field' => 'user_belongsto_department_relationship',
                'type' => 'relationship',
                'display_name' => 'departments',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Department","table":"departments","type":"belongsTo","column":"department_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 17,
            ),
            81 => 
            array (
                'id' => 136,
                'data_type_id' => 16,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 18,
            ),
            82 => 
            array (
                'id' => 137,
                'data_type_id' => 16,
                'field' => 'user_belongsto_grade_relationship',
                'type' => 'relationship',
                'display_name' => 'grades',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Grade","table":"grades","type":"belongsTo","column":"grade_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 19,
            ),
            83 => 
            array (
                'id' => 138,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            84 => 
            array (
                'id' => 139,
                'data_type_id' => 17,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            85 => 
            array (
                'id' => 140,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            86 => 
            array (
                'id' => 141,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            87 => 
            array (
                'id' => 142,
                'data_type_id' => 17,
                'field' => 'grade_hasmany_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"hasMany","column":"grade_id","key":"id","label":"email","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            88 => 
            array (
                'id' => 143,
                'data_type_id' => 12,
                'field' => 'modelname',
                'type' => 'text',
                'display_name' => 'Modelname',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            89 => 
            array (
                'id' => 144,
                'data_type_id' => 12,
                'field' => 'pwbname',
                'type' => 'text',
                'display_name' => 'Pwbname',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            90 => 
            array (
                'id' => 145,
                'data_type_id' => 8,
                'field' => 'scanner_belongsto_lineprocess_relationship',
                'type' => 'relationship',
                'display_name' => 'lineprocesses',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Lineprocess","table":"lineprocesses","type":"belongsTo","column":"lineprocess_id","key":"id","label":"id","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            91 => 
            array (
                'id' => 146,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            92 => 
            array (
                'id' => 147,
                'data_type_id' => 18,
                'field' => 'board_id',
                'type' => 'text',
                'display_name' => 'Board Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            93 => 
            array (
                'id' => 148,
                'data_type_id' => 18,
                'field' => 'guid_master',
                'type' => 'text',
                'display_name' => 'Guid Master',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            94 => 
            array (
                'id' => 149,
                'data_type_id' => 18,
                'field' => 'guid_ticket',
                'type' => 'text',
                'display_name' => 'Guid Ticket',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            95 => 
            array (
                'id' => 150,
                'data_type_id' => 18,
                'field' => 'scanner_id',
                'type' => 'text',
                'display_name' => 'Scanner Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            96 => 
            array (
                'id' => 151,
                'data_type_id' => 18,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            97 => 
            array (
                'id' => 152,
                'data_type_id' => 18,
                'field' => 'scan_nik',
                'type' => 'text',
                'display_name' => 'Scan Nik',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            98 => 
            array (
                'id' => 153,
                'data_type_id' => 18,
                'field' => 'judge',
                'type' => 'text',
                'display_name' => 'Judge',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            99 => 
            array (
                'id' => 154,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            100 => 
            array (
                'id' => 155,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 10,
            ),
            101 => 
            array (
                'id' => 156,
                'data_type_id' => 18,
                'field' => 'board_belongsto_scanner_relationship',
                'type' => 'relationship',
                'display_name' => 'scanners',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Scanner","table":"scanners","type":"belongsTo","column":"scanner_id","key":"id","label":"ip_address","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 11,
            ),
            102 => 
            array (
                'id' => 166,
                'data_type_id' => 21,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            103 => 
            array (
                'id' => 167,
                'data_type_id' => 21,
                'field' => 'dummy_column',
                'type' => 'text',
                'display_name' => 'Dummy Column',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            104 => 
            array (
                'id' => 168,
                'data_type_id' => 21,
                'field' => 'table_name',
                'type' => 'text',
                'display_name' => 'Table Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            105 => 
            array (
                'id' => 169,
                'data_type_id' => 21,
                'field' => 'code_prefix',
                'type' => 'text',
                'display_name' => 'Code Prefix',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            106 => 
            array (
                'id' => 170,
                'data_type_id' => 21,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            107 => 
            array (
                'id' => 171,
                'data_type_id' => 21,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            108 => 
            array (
                'id' => 172,
                'data_type_id' => 21,
                'field' => 'column_setting_belongstomany_lineprocess_relationship',
                'type' => 'relationship',
                'display_name' => 'lineprocesses',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Lineprocess","table":"lineprocesses","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"column_setting_lineprocess","pivot":"1","taggable":"on"}',
                'order' => 7,
            ),
            109 => 
            array (
                'id' => 173,
                'data_type_id' => 11,
                'field' => 'linetype_belongstomany_column_setting_relationship',
                'type' => 'relationship',
                'display_name' => 'column_settings',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\ColumnSetting","table":"column_settings","type":"belongsToMany","column":"id","key":"id","label":"code_prefix","pivot_table":"column_setting_lineprocess","pivot":"1","taggable":"on"}',
                'order' => 9,
            ),
            110 => 
            array (
                'id' => 174,
                'data_type_id' => 10,
                'field' => 'lineprocess_belongstomany_column_setting_relationship',
                'type' => 'relationship',
                'display_name' => 'column_settings',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\ColumnSetting","table":"column_settings","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"column_setting_lineprocess","pivot":"1","taggable":"on"}',
                'order' => 9,
            ),
            111 => 
            array (
                'id' => 175,
                'data_type_id' => 21,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            112 => 
            array (
                'id' => 177,
                'data_type_id' => 12,
                'field' => 'sequence_belongstomany_lineprocess_relationship',
                'type' => 'relationship',
                'display_name' => 'lineprocesses',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Lineprocess","table":"lineprocesses","type":"belongsToMany","column":"id","key":"id","label":"id","pivot_table":"lineprocess_sequence","pivot":"1","taggable":"on"}',
                'order' => 10,
            ),
            113 => 
            array (
                'id' => 178,
                'data_type_id' => 23,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            114 => 
            array (
                'id' => 179,
                'data_type_id' => 23,
                'field' => 'code',
                'type' => 'text',
                'display_name' => 'Code',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            115 => 
            array (
                'id' => 180,
                'data_type_id' => 23,
                'field' => 'line_id',
                'type' => 'text',
                'display_name' => 'Line Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            116 => 
            array (
                'id' => 181,
                'data_type_id' => 23,
                'field' => 'last_no',
                'type' => 'text',
                'display_name' => 'Last No',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            117 => 
            array (
                'id' => 182,
                'data_type_id' => 23,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            118 => 
            array (
                'id' => 183,
                'data_type_id' => 23,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            119 => 
            array (
                'id' => 184,
                'data_type_id' => 23,
                'field' => 'ticket_master_belongsto_line_relationship',
                'type' => 'relationship',
                'display_name' => 'lines',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Line","table":"lines","type":"belongsTo","column":"line_id","key":"id","label":"name","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            120 => 
            array (
                'id' => 185,
                'data_type_id' => 23,
                'field' => 'ticket_master_belongsto_column_setting_relationship',
                'type' => 'relationship',
                'display_name' => 'Code',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\ColumnSetting","table":"column_settings","type":"belongsTo","column":"code","key":"code_prefix","label":"code_prefix","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            121 => 
            array (
                'id' => 186,
                'data_type_id' => 10,
                'field' => 'lineprocess_hasone_scanner_relationship',
                'type' => 'relationship',
                'display_name' => 'scanners',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Scanner","table":"scanners","type":"hasOne","column":"lineprocess_id","key":"id","label":"id","pivot_table":"accesses","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            122 => 
            array (
                'id' => 187,
                'data_type_id' => 24,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            123 => 
            array (
                'id' => 188,
                'data_type_id' => 24,
                'field' => 'ticket_no',
                'type' => 'text',
                'display_name' => 'Ticket No',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            124 => 
            array (
                'id' => 189,
                'data_type_id' => 24,
                'field' => 'guid_master',
                'type' => 'text',
                'display_name' => 'Guid Master',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            125 => 
            array (
                'id' => 190,
                'data_type_id' => 24,
                'field' => 'guid_ticket',
                'type' => 'text',
                'display_name' => 'Guid Ticket',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            126 => 
            array (
                'id' => 191,
                'data_type_id' => 24,
                'field' => 'scanner_id',
                'type' => 'text',
                'display_name' => 'Scanner Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            127 => 
            array (
                'id' => 192,
                'data_type_id' => 24,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            128 => 
            array (
                'id' => 193,
                'data_type_id' => 24,
                'field' => 'scan_nik',
                'type' => 'text',
                'display_name' => 'Scan Nik',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            129 => 
            array (
                'id' => 194,
                'data_type_id' => 24,
                'field' => 'judge',
                'type' => 'text',
                'display_name' => 'Judge',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            130 => 
            array (
                'id' => 195,
                'data_type_id' => 24,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            131 => 
            array (
                'id' => 196,
                'data_type_id' => 24,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 10,
            ),
            132 => 
            array (
                'id' => 197,
                'data_type_id' => 18,
                'field' => 'modelname',
                'type' => 'text',
                'display_name' => 'Modelname',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            133 => 
            array (
                'id' => 198,
                'data_type_id' => 18,
                'field' => 'lotno',
                'type' => 'text',
                'display_name' => 'Lotno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            134 => 
            array (
                'id' => 199,
                'data_type_id' => 25,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            135 => 
            array (
                'id' => 200,
                'data_type_id' => 25,
                'field' => 'ticket_no_master',
                'type' => 'text',
                'display_name' => 'Ticket No Master',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            136 => 
            array (
                'id' => 201,
                'data_type_id' => 25,
                'field' => 'guid_master',
                'type' => 'text',
                'display_name' => 'Guid Master',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            137 => 
            array (
                'id' => 202,
                'data_type_id' => 25,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            138 => 
            array (
                'id' => 203,
                'data_type_id' => 25,
                'field' => 'scanner_id',
                'type' => 'text',
                'display_name' => 'Scanner Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            139 => 
            array (
                'id' => 204,
                'data_type_id' => 25,
                'field' => 'scan_nik',
                'type' => 'text',
                'display_name' => 'Scan Nik',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            140 => 
            array (
                'id' => 205,
                'data_type_id' => 25,
                'field' => 'serial_no',
                'type' => 'text',
                'display_name' => 'Serial No',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            141 => 
            array (
                'id' => 206,
                'data_type_id' => 25,
                'field' => 'judge',
                'type' => 'text',
                'display_name' => 'Judge',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            142 => 
            array (
                'id' => 207,
                'data_type_id' => 25,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            143 => 
            array (
                'id' => 208,
                'data_type_id' => 25,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 10,
            ),
            144 => 
            array (
                'id' => 209,
                'data_type_id' => 26,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            145 => 
            array (
                'id' => 210,
                'data_type_id' => 26,
                'field' => 'line_id',
                'type' => 'text',
                'display_name' => 'Line Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            146 => 
            array (
                'id' => 211,
                'data_type_id' => 26,
                'field' => 'lineprocess_id',
                'type' => 'text',
                'display_name' => 'Lineprocess Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            147 => 
            array (
                'id' => 212,
                'data_type_id' => 26,
                'field' => 'unique_id',
                'type' => 'text',
                'display_name' => 'Unique Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            148 => 
            array (
                'id' => 213,
                'data_type_id' => 26,
                'field' => 'supp_code',
                'type' => 'text',
                'display_name' => 'Supp Code',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            149 => 
            array (
                'id' => 214,
                'data_type_id' => 26,
                'field' => 'part_no',
                'type' => 'text',
                'display_name' => 'Part No',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            150 => 
            array (
                'id' => 215,
                'data_type_id' => 26,
                'field' => 'po',
                'type' => 'text',
                'display_name' => 'Po',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            151 => 
            array (
                'id' => 216,
                'data_type_id' => 26,
                'field' => 'production_date',
                'type' => 'text',
                'display_name' => 'Production Date',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            152 => 
            array (
                'id' => 217,
                'data_type_id' => 26,
                'field' => 'lotno',
                'type' => 'text',
                'display_name' => 'Lotno',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            153 => 
            array (
                'id' => 218,
                'data_type_id' => 26,
                'field' => 'qty',
                'type' => 'text',
                'display_name' => 'Qty',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 10,
            ),
            154 => 
            array (
                'id' => 219,
                'data_type_id' => 26,
                'field' => 'scan_nik',
                'type' => 'text',
                'display_name' => 'Scan Nik',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 11,
            ),
            155 => 
            array (
                'id' => 220,
                'data_type_id' => 26,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 12,
            ),
            156 => 
            array (
                'id' => 221,
                'data_type_id' => 26,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 13,
            ),
            157 => 
            array (
                'id' => 227,
                'data_type_id' => 28,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            158 => 
            array (
                'id' => 228,
                'data_type_id' => 28,
                'field' => 'unique_id',
                'type' => 'text',
                'display_name' => 'Unique Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            159 => 
            array (
                'id' => 229,
                'data_type_id' => 28,
                'field' => 'dummy_id',
                'type' => 'text',
                'display_name' => 'Dummy Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            160 => 
            array (
                'id' => 230,
                'data_type_id' => 28,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            161 => 
            array (
                'id' => 231,
                'data_type_id' => 28,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            162 => 
            array (
                'id' => 232,
                'data_type_id' => 30,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            163 => 
            array (
                'id' => 233,
                'data_type_id' => 30,
                'field' => 'code',
                'type' => 'text',
                'display_name' => 'Code',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            164 => 
            array (
                'id' => 234,
                'data_type_id' => 30,
                'field' => 'category',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            165 => 
            array (
                'id' => 235,
                'data_type_id' => 30,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            166 => 
            array (
                'id' => 236,
                'data_type_id' => 30,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            167 => 
            array (
                'id' => 237,
                'data_type_id' => 30,
                'field' => 'symptom_belongstomany_master_relationship',
                'type' => 'relationship',
                'display_name' => 'masters',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Master","table":"masters","type":"belongsToMany","column":"id","key":"id","label":"id","pivot_table":"master_symptom","pivot":"1","taggable":null}',
                'order' => 6,
            ),
            168 => 
            array (
                'id' => 238,
                'data_type_id' => 25,
                'field' => 'master_belongstomany_symptom_relationship',
                'type' => 'relationship',
                'display_name' => 'symptoms',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Symptom","table":"symptoms","type":"belongsToMany","column":"id","key":"id","label":"category","pivot_table":"master_symptom","pivot":"1","taggable":null}',
                'order' => 11,
            ),
        ));
        
        
    }
}